name: FeROS CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    name: Build AArch64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install AArch64 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu

      - name: Build FeROS
        run: make CROSS_COMPILE=aarch64-linux-gnu-

      - name: Inspect FeROS build
        run: make CROSS_COMPILE=aarch64-linux-gnu- inspect
